name: deploy_to_cocoapods 

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Deploy to Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          echo "LIB_VERSION=`git describe --abbrev=0`" >> "$GITHUB_ENV"
          echo "${{ env.LIB_VERSION }}"
          pod lib lint --allow-warnings
          pod trunk push --alow-warnings